/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaraaRouteImport } from './routes/varaa'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaraaKiitosRouteImport } from './routes/varaa.kiitos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminVarauksetRouteImport } from './routes/_authenticated/admin.varaukset'
import { Route as AuthenticatedAdminSulkemisetRouteImport } from './routes/_authenticated/admin.sulkemiset'
import { Route as AuthenticatedAdminSisaltoRouteImport } from './routes/_authenticated/admin.sisalto'
import { Route as AuthenticatedAdminPaikatRouteImport } from './routes/_authenticated/admin.paikat'
import { Route as AuthenticatedAdminKalenteriRouteImport } from './routes/_authenticated/admin.kalenteri'
import { Route as AuthenticatedAdminAsetuksetRouteImport } from './routes/_authenticated/admin.asetukset'
import { Route as AuthenticatedAdminSisaltoIndexRouteImport } from './routes/_authenticated/admin.sisalto.index'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'
import { Route as AuthenticatedAdminSisaltoYleisetRouteImport } from './routes/_authenticated/admin.sisalto.yleiset'
import { Route as AuthenticatedAdminSisaltoMajoituksetRouteImport } from './routes/_authenticated/admin.sisalto.majoitukset'
import { Route as AuthenticatedAdminSisaltoEtusivuRouteImport } from './routes/_authenticated/admin.sisalto.etusivu'
import { Route as AuthenticatedAdminSisaltoArvostelutRouteImport } from './routes/_authenticated/admin.sisalto.arvostelut'
import { Route as AuthenticatedAdminSisaltoAlueRouteImport } from './routes/_authenticated/admin.sisalto.alue'

const VaraaRoute = VaraaRouteImport.update({
  id: '/varaa',
  path: '/varaa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaraaKiitosRoute = VaraaKiitosRouteImport.update({
  id: '/kiitos',
  path: '/kiitos',
  getParentRoute: () => VaraaRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVarauksetRoute =
  AuthenticatedAdminVarauksetRouteImport.update({
    id: '/varaukset',
    path: '/varaukset',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSulkemisetRoute =
  AuthenticatedAdminSulkemisetRouteImport.update({
    id: '/sulkemiset',
    path: '/sulkemiset',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSisaltoRoute =
  AuthenticatedAdminSisaltoRouteImport.update({
    id: '/sisalto',
    path: '/sisalto',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaikatRoute =
  AuthenticatedAdminPaikatRouteImport.update({
    id: '/paikat',
    path: '/paikat',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKalenteriRoute =
  AuthenticatedAdminKalenteriRouteImport.update({
    id: '/kalenteri',
    path: '/kalenteri',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAsetuksetRoute =
  AuthenticatedAdminAsetuksetRouteImport.update({
    id: '/asetukset',
    path: '/asetukset',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSisaltoIndexRoute =
  AuthenticatedAdminSisaltoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSisaltoRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSisaltoYleisetRoute =
  AuthenticatedAdminSisaltoYleisetRouteImport.update({
    id: '/yleiset',
    path: '/yleiset',
    getParentRoute: () => AuthenticatedAdminSisaltoRoute,
  } as any)
const AuthenticatedAdminSisaltoMajoituksetRoute =
  AuthenticatedAdminSisaltoMajoituksetRouteImport.update({
    id: '/majoitukset',
    path: '/majoitukset',
    getParentRoute: () => AuthenticatedAdminSisaltoRoute,
  } as any)
const AuthenticatedAdminSisaltoEtusivuRoute =
  AuthenticatedAdminSisaltoEtusivuRouteImport.update({
    id: '/etusivu',
    path: '/etusivu',
    getParentRoute: () => AuthenticatedAdminSisaltoRoute,
  } as any)
const AuthenticatedAdminSisaltoArvostelutRoute =
  AuthenticatedAdminSisaltoArvostelutRouteImport.update({
    id: '/arvostelut',
    path: '/arvostelut',
    getParentRoute: () => AuthenticatedAdminSisaltoRoute,
  } as any)
const AuthenticatedAdminSisaltoAlueRoute =
  AuthenticatedAdminSisaltoAlueRouteImport.update({
    id: '/alue',
    path: '/alue',
    getParentRoute: () => AuthenticatedAdminSisaltoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/varaa': typeof VaraaRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/varaa/kiitos': typeof VaraaKiitosRoute
  '/admin/asetukset': typeof AuthenticatedAdminAsetuksetRoute
  '/admin/kalenteri': typeof AuthenticatedAdminKalenteriRoute
  '/admin/paikat': typeof AuthenticatedAdminPaikatRoute
  '/admin/sisalto': typeof AuthenticatedAdminSisaltoRouteWithChildren
  '/admin/sulkemiset': typeof AuthenticatedAdminSulkemisetRoute
  '/admin/varaukset': typeof AuthenticatedAdminVarauksetRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/sisalto/alue': typeof AuthenticatedAdminSisaltoAlueRoute
  '/admin/sisalto/arvostelut': typeof AuthenticatedAdminSisaltoArvostelutRoute
  '/admin/sisalto/etusivu': typeof AuthenticatedAdminSisaltoEtusivuRoute
  '/admin/sisalto/majoitukset': typeof AuthenticatedAdminSisaltoMajoituksetRoute
  '/admin/sisalto/yleiset': typeof AuthenticatedAdminSisaltoYleisetRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/admin/sisalto/': typeof AuthenticatedAdminSisaltoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/varaa': typeof VaraaRouteWithChildren
  '/varaa/kiitos': typeof VaraaKiitosRoute
  '/admin/asetukset': typeof AuthenticatedAdminAsetuksetRoute
  '/admin/kalenteri': typeof AuthenticatedAdminKalenteriRoute
  '/admin/paikat': typeof AuthenticatedAdminPaikatRoute
  '/admin/sulkemiset': typeof AuthenticatedAdminSulkemisetRoute
  '/admin/varaukset': typeof AuthenticatedAdminVarauksetRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/sisalto/alue': typeof AuthenticatedAdminSisaltoAlueRoute
  '/admin/sisalto/arvostelut': typeof AuthenticatedAdminSisaltoArvostelutRoute
  '/admin/sisalto/etusivu': typeof AuthenticatedAdminSisaltoEtusivuRoute
  '/admin/sisalto/majoitukset': typeof AuthenticatedAdminSisaltoMajoituksetRoute
  '/admin/sisalto/yleiset': typeof AuthenticatedAdminSisaltoYleisetRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/admin/sisalto': typeof AuthenticatedAdminSisaltoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/varaa': typeof VaraaRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/varaa/kiitos': typeof VaraaKiitosRoute
  '/_authenticated/admin/asetukset': typeof AuthenticatedAdminAsetuksetRoute
  '/_authenticated/admin/kalenteri': typeof AuthenticatedAdminKalenteriRoute
  '/_authenticated/admin/paikat': typeof AuthenticatedAdminPaikatRoute
  '/_authenticated/admin/sisalto': typeof AuthenticatedAdminSisaltoRouteWithChildren
  '/_authenticated/admin/sulkemiset': typeof AuthenticatedAdminSulkemisetRoute
  '/_authenticated/admin/varaukset': typeof AuthenticatedAdminVarauksetRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/sisalto/alue': typeof AuthenticatedAdminSisaltoAlueRoute
  '/_authenticated/admin/sisalto/arvostelut': typeof AuthenticatedAdminSisaltoArvostelutRoute
  '/_authenticated/admin/sisalto/etusivu': typeof AuthenticatedAdminSisaltoEtusivuRoute
  '/_authenticated/admin/sisalto/majoitukset': typeof AuthenticatedAdminSisaltoMajoituksetRoute
  '/_authenticated/admin/sisalto/yleiset': typeof AuthenticatedAdminSisaltoYleisetRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/_authenticated/admin/sisalto/': typeof AuthenticatedAdminSisaltoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/varaa'
    | '/admin'
    | '/varaa/kiitos'
    | '/admin/asetukset'
    | '/admin/kalenteri'
    | '/admin/paikat'
    | '/admin/sisalto'
    | '/admin/sulkemiset'
    | '/admin/varaukset'
    | '/admin/'
    | '/admin/sisalto/alue'
    | '/admin/sisalto/arvostelut'
    | '/admin/sisalto/etusivu'
    | '/admin/sisalto/majoitukset'
    | '/admin/sisalto/yleiset'
    | '/api/public/media/$'
    | '/admin/sisalto/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/varaa'
    | '/varaa/kiitos'
    | '/admin/asetukset'
    | '/admin/kalenteri'
    | '/admin/paikat'
    | '/admin/sulkemiset'
    | '/admin/varaukset'
    | '/admin'
    | '/admin/sisalto/alue'
    | '/admin/sisalto/arvostelut'
    | '/admin/sisalto/etusivu'
    | '/admin/sisalto/majoitukset'
    | '/admin/sisalto/yleiset'
    | '/api/public/media/$'
    | '/admin/sisalto'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/varaa'
    | '/_authenticated/admin'
    | '/varaa/kiitos'
    | '/_authenticated/admin/asetukset'
    | '/_authenticated/admin/kalenteri'
    | '/_authenticated/admin/paikat'
    | '/_authenticated/admin/sisalto'
    | '/_authenticated/admin/sulkemiset'
    | '/_authenticated/admin/varaukset'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/sisalto/alue'
    | '/_authenticated/admin/sisalto/arvostelut'
    | '/_authenticated/admin/sisalto/etusivu'
    | '/_authenticated/admin/sisalto/majoitukset'
    | '/_authenticated/admin/sisalto/yleiset'
    | '/api/public/media/$'
    | '/_authenticated/admin/sisalto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VaraaRoute: typeof VaraaRouteWithChildren
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/varaa': {
      id: '/varaa'
      path: '/varaa'
      fullPath: '/varaa'
      preLoaderRoute: typeof VaraaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varaa/kiitos': {
      id: '/varaa/kiitos'
      path: '/kiitos'
      fullPath: '/varaa/kiitos'
      preLoaderRoute: typeof VaraaKiitosRouteImport
      parentRoute: typeof VaraaRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/varaukset': {
      id: '/_authenticated/admin/varaukset'
      path: '/varaukset'
      fullPath: '/admin/varaukset'
      preLoaderRoute: typeof AuthenticatedAdminVarauksetRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sulkemiset': {
      id: '/_authenticated/admin/sulkemiset'
      path: '/sulkemiset'
      fullPath: '/admin/sulkemiset'
      preLoaderRoute: typeof AuthenticatedAdminSulkemisetRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sisalto': {
      id: '/_authenticated/admin/sisalto'
      path: '/sisalto'
      fullPath: '/admin/sisalto'
      preLoaderRoute: typeof AuthenticatedAdminSisaltoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/paikat': {
      id: '/_authenticated/admin/paikat'
      path: '/paikat'
      fullPath: '/admin/paikat'
      preLoaderRoute: typeof AuthenticatedAdminPaikatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kalenteri': {
      id: '/_authenticated/admin/kalenteri'
      path: '/kalenteri'
      fullPath: '/admin/kalenteri'
      preLoaderRoute: typeof AuthenticatedAdminKalenteriRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/asetukset': {
      id: '/_authenticated/admin/asetukset'
      path: '/asetukset'
      fullPath: '/admin/asetukset'
      preLoaderRoute: typeof AuthenticatedAdminAsetuksetRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sisalto/': {
      id: '/_authenticated/admin/sisalto/'
      path: '/'
      fullPath: '/admin/sisalto/'
      preLoaderRoute: typeof AuthenticatedAdminSisaltoIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSisaltoRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/sisalto/yleiset': {
      id: '/_authenticated/admin/sisalto/yleiset'
      path: '/yleiset'
      fullPath: '/admin/sisalto/yleiset'
      preLoaderRoute: typeof AuthenticatedAdminSisaltoYleisetRouteImport
      parentRoute: typeof AuthenticatedAdminSisaltoRoute
    }
    '/_authenticated/admin/sisalto/majoitukset': {
      id: '/_authenticated/admin/sisalto/majoitukset'
      path: '/majoitukset'
      fullPath: '/admin/sisalto/majoitukset'
      preLoaderRoute: typeof AuthenticatedAdminSisaltoMajoituksetRouteImport
      parentRoute: typeof AuthenticatedAdminSisaltoRoute
    }
    '/_authenticated/admin/sisalto/etusivu': {
      id: '/_authenticated/admin/sisalto/etusivu'
      path: '/etusivu'
      fullPath: '/admin/sisalto/etusivu'
      preLoaderRoute: typeof AuthenticatedAdminSisaltoEtusivuRouteImport
      parentRoute: typeof AuthenticatedAdminSisaltoRoute
    }
    '/_authenticated/admin/sisalto/arvostelut': {
      id: '/_authenticated/admin/sisalto/arvostelut'
      path: '/arvostelut'
      fullPath: '/admin/sisalto/arvostelut'
      preLoaderRoute: typeof AuthenticatedAdminSisaltoArvostelutRouteImport
      parentRoute: typeof AuthenticatedAdminSisaltoRoute
    }
    '/_authenticated/admin/sisalto/alue': {
      id: '/_authenticated/admin/sisalto/alue'
      path: '/alue'
      fullPath: '/admin/sisalto/alue'
      preLoaderRoute: typeof AuthenticatedAdminSisaltoAlueRouteImport
      parentRoute: typeof AuthenticatedAdminSisaltoRoute
    }
  }
}

interface AuthenticatedAdminSisaltoRouteChildren {
  AuthenticatedAdminSisaltoAlueRoute: typeof AuthenticatedAdminSisaltoAlueRoute
  AuthenticatedAdminSisaltoArvostelutRoute: typeof AuthenticatedAdminSisaltoArvostelutRoute
  AuthenticatedAdminSisaltoEtusivuRoute: typeof AuthenticatedAdminSisaltoEtusivuRoute
  AuthenticatedAdminSisaltoMajoituksetRoute: typeof AuthenticatedAdminSisaltoMajoituksetRoute
  AuthenticatedAdminSisaltoYleisetRoute: typeof AuthenticatedAdminSisaltoYleisetRoute
  AuthenticatedAdminSisaltoIndexRoute: typeof AuthenticatedAdminSisaltoIndexRoute
}

const AuthenticatedAdminSisaltoRouteChildren: AuthenticatedAdminSisaltoRouteChildren =
  {
    AuthenticatedAdminSisaltoAlueRoute: AuthenticatedAdminSisaltoAlueRoute,
    AuthenticatedAdminSisaltoArvostelutRoute:
      AuthenticatedAdminSisaltoArvostelutRoute,
    AuthenticatedAdminSisaltoEtusivuRoute:
      AuthenticatedAdminSisaltoEtusivuRoute,
    AuthenticatedAdminSisaltoMajoituksetRoute:
      AuthenticatedAdminSisaltoMajoituksetRoute,
    AuthenticatedAdminSisaltoYleisetRoute:
      AuthenticatedAdminSisaltoYleisetRoute,
    AuthenticatedAdminSisaltoIndexRoute: AuthenticatedAdminSisaltoIndexRoute,
  }

const AuthenticatedAdminSisaltoRouteWithChildren =
  AuthenticatedAdminSisaltoRoute._addFileChildren(
    AuthenticatedAdminSisaltoRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAsetuksetRoute: typeof AuthenticatedAdminAsetuksetRoute
  AuthenticatedAdminKalenteriRoute: typeof AuthenticatedAdminKalenteriRoute
  AuthenticatedAdminPaikatRoute: typeof AuthenticatedAdminPaikatRoute
  AuthenticatedAdminSisaltoRoute: typeof AuthenticatedAdminSisaltoRouteWithChildren
  AuthenticatedAdminSulkemisetRoute: typeof AuthenticatedAdminSulkemisetRoute
  AuthenticatedAdminVarauksetRoute: typeof AuthenticatedAdminVarauksetRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAsetuksetRoute: AuthenticatedAdminAsetuksetRoute,
  AuthenticatedAdminKalenteriRoute: AuthenticatedAdminKalenteriRoute,
  AuthenticatedAdminPaikatRoute: AuthenticatedAdminPaikatRoute,
  AuthenticatedAdminSisaltoRoute: AuthenticatedAdminSisaltoRouteWithChildren,
  AuthenticatedAdminSulkemisetRoute: AuthenticatedAdminSulkemisetRoute,
  AuthenticatedAdminVarauksetRoute: AuthenticatedAdminVarauksetRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface VaraaRouteChildren {
  VaraaKiitosRoute: typeof VaraaKiitosRoute
}

const VaraaRouteChildren: VaraaRouteChildren = {
  VaraaKiitosRoute: VaraaKiitosRoute,
}

const VaraaRouteWithChildren = VaraaRoute._addFileChildren(VaraaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VaraaRoute: VaraaRouteWithChildren,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
